name: ci

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Train tiny model
        run: python scripts/train.py

      - name: Run tests
        run: pytest -q

      - name: Set image name (lowercase)
        run: |
          OWNER_LC="${GITHUB_REPOSITORY_OWNER,,}"           # -> davidthehero
          REPO_LC="$(basename "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')"  # -> sentiment-ci-cd
          echo "IMAGE=ghcr.io/${OWNER_LC}/${REPO_LC}/sentiment-api" >> $GITHUB_ENV

      - name: Log in to GHCR (GITHUB_TOKEN)
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & (push on main) multi-arch
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.IMAGE }}:latest

      - name: Smoke test container (run image & check /health)
        if: github.ref == 'refs/heads/main'
        run: |
          docker run -d --rm -p 8000:8000 --name api ${{ env.IMAGE }}:latest
          # wait for boot (retry up to ~10s)
          for i in {1..10}; do
            curl -fsS localhost:8000/health && break || sleep 1
          done
          curl -fsS localhost:8000/health
          docker rm -f api